objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Expense__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date of Expense</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expense_Amount__c</fullName>
        <label>Expense Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense_Owner__c</fullName>
        <label>Expense Owner</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Arpit</fullName>
                </value>
                <value>
                    <fullName>Harsh</fullName>
                </value>
                <value>
                    <fullName>Krutarth</fullName>
                </value>
                <value>
                    <fullName>Palak</fullName>
                </value>
                <value>
                    <fullName>Purav</fullName>
                </value>
                <value>
                    <fullName>Rutvi</fullName>
                </value>
                <value>
                    <fullName>Tirth</fullName>
                </value>
                <value>
                    <fullName>Urvish</fullName>
                </value>
                <value>
                    <fullName>Nirali</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expense_Type__c</fullName>
        <label>Expense Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Breakfast</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Dinner</fullName>
                </value>
                <value>
                    <fullName>Coffee/Snacks</fullName>
                </value>
                <value>
                    <fullName>Activity Fees</fullName>
                </value>
                <value>
                    <fullName>Uber/Lyft</fullName>
                </value>
                <value>
                    <fullName>Car Rental</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Air Fare</fullName>
                </value>
                <value>
                    <fullName>Liquor</fullName>
                </value>
                <value>
                    <fullName>Stay during the trip</fullName>
                </value>
                <value>
                    <fullName>Personal Shopping</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Expense__c</fullName>
        <label>Parent Expense</label>
        <referenceTo>Total_Expense__c</referenceTo>
        <relationshipLabel>Expense</relationshipLabel>
        <relationshipName>Expense</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Share_Expense_with_Everybody__c</fullName>
        <label>Share Expense with Everybody</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Urvish__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Urvish</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Total_Expense__c.object
<CustomObject>
    <label>Total Expense</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Total Expense</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ExpenseTrackerTriggerHandlerTest.cls
@isTest(SeeAllData=true)
private class ExpenseTrackerTriggerHandlerTest 
{
    @isTest static void testExpenseTracker() 
    {
        Total_Expense__c t = new Total_Expense__c();
        t.name = 'RM';
        insert t;
        
        Expense__c e1 = new Expense__c();
        e1.recordtypeid = '0121C000001l9mg';
        e1.name = 't1';
        e1.expense_owner__c = 'Urvish';
        e1.expense_type__c = 'Lunch';
        e1.expense_amount__c = 400.00;
        e1.Parent_Expense__c =  t.id;
        e1.Date_of_Expense__c = date.today();
        insert e1;
        
        Expense__c e2 = new Expense__c();
        e2.recordtypeid = '0121C000001l9ml';
        e2.name = 't2';
        e2.expense_owner__c = 'Urvish';
        e2.expense_type__c = 'Lunch';
        e2.expense_amount__c = 400.00;
        e2.Parent_Expense__c =  t.id;
        e2.Share_Expense_with_Everybody__c = 'Yes';
        e2.Date_of_Expense__c = date.today();
        insert e2;
        
        Expense__c e3 = new Expense__c();
        e3.recordtypeid = '0121C000001l9mq';
        e3.name = 't3';
        e3.expense_owner__c = 'Urvish';
        e3.expense_type__c = 'Lunch';
        e3.expense_amount__c = 400.00;
        e3.Parent_Expense__c =  t.id;
        e3.Date_of_Expense__c = date.today();
        e3.urvish__c = 400.00;
        insert e3;
    }
}